#!/usr/bin/env python
# isort:skip_file

import os
import sys
import subprocess

print('Sage Git Releasemanagement')

basedir = os.path.dirname(os.path.realpath(__file__))
print('basedir', basedir)
os.environ['PYTHONPATH'] = basedir

print('argv', sys.argv)

python = os.path.join(basedir, 'tools', 'bin', 'python')
os.execv(
    python,
    [
        python,
        '-m',
        'git_sage.cmdline',
        *sys.argv[1:]
    ],
)



